from pathlib import Path
p=Path('outputs/udl-prototype.html');s=p.read_text(encoding='utf-8')
s=s.replace("players.forEach((p,i)=>p.rank=i&&p.points===players[i-1].points?players[i-1].rank:i+1);","players.forEach((p,i)=>p.rank=i+1);")
s=s.replace('Los empates comparten puesto.','Los puestos son ordinales; los desempates definitivos se definirán más adelante.')
s=s.replace('Completados en Uruguay<span','Lista uruguaya<span').replace('Solo niveles con al menos una completación uruguaya aceptada al 100%.','Extreme Demons completados por jugadores uruguayos, ordenados por dificultad.')
s=s.replace('<span class="muted small">Actividad reciente</span>','<a class="text-link" href="#activity">Ver actividad →</a>')
s=s.replace('<td class="player-name">${p.name}</td>','<td class="player-name"><a class="player-link" href="#player/${encodeURIComponent(p.name)}">${p.name}</a></td>')
s=s.replace('<strong>${p[0]}</strong>','<a class="player-link" href="#player/${encodeURIComponent(p[0])}"><strong>${p[0]}</strong></a>')
s=s.replace('<span>${name}</span>','<a class="player-link" href="#player/${encodeURIComponent(name)}">${name}</a>').replace('>Video ↗</button>','>Ver video ↗</button>')
a=s.index('<div class="detail-heading">',s.index('function detail('));b=s.index('<div class="detail-grid">',a)
s=s[:a]+'''<div class="detail-heading refined-heading"><div><div class="eyebrow">AREDL #${l.aredlRank}</div><h1>${l.name}<span class="blue">.</span></h1><p>por ${l.creator}</p></div><div class="detail-rating"><span class="local-placement ${rankClass(l.rank)}">#${String(l.rank).padStart(2,'0')} <small>Uruguay</small></span><strong>${l.pts} <small>pts UY</small></strong></div></div>'''+s[b:]
s=s.replace('<div class="badges" aria-label="Etiquetas del nivel">','<h3 class="progress-title">Etiquetas</h3><div class="badges" aria-label="Etiquetas del nivel">')
s=s.replace('</div>${victors(l).map', '</div><p class="muted small record-subtitle">${victors(l).length} jugadores uruguayos completaron este nivel.</p>${victors(l).map')
s=s.replace('>Récords de progreso</h3>','>Progresos</h3>').replace('>Historial en Uruguay</h2>','>Historial</h2>')
pos=s.index('let noticeTimer;')
s=s[:pos]+'''
function bindVideoButtons(){document.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>notify('Video de ejemplo: el enlace de YouTube se conectará en una próxima etapa.'))}
function profile(name){const p=players.find(p=>p.name===name);if(!p){main.innerHTML='<h1>Jugador no encontrado</h1><a class="back" href="#players">← Jugadores</a>';return}const completed=uyLevels.filter(l=>victors(l).some(r=>r.player===name));const hardest=completed[0];const progress=levels.flatMap((l,id)=>l.records.filter(r=>r.player===name&&r.country==='UY'&&r.approved&&r.pct<100).map(r=>({...r,level:l,id})));main.innerHTML=`<a class="back" href="#players">← Jugadores</a><div class="profile-heading"><div class="eyebrow">Jugador uruguayo</div><h1>${p.name}<span class="blue">.</span></h1><div class="profile-stats"><div><span class="muted small">Puesto en Uruguay</span><strong class="${rankClass(p.rank)}">#${String(p.rank).padStart(2,'0')}</strong></div><div><span class="muted small">Puntos UY</span><strong>${p.points} <small>pts</small></strong></div><div><span class="muted small">Extreme Demons</span><strong>${p.extremes}</strong></div></div></div><section class="profile-section"><h2>Nivel más difícil</h2>${hardest?`<a class="hardest-link" href="#level/${hardest.id}">${hardest.name} <span aria-hidden="true">↗</span></a><p class="small blue">AREDL #${hardest.aredlRank} · #${String(hardest.rank).padStart(2,'0')} UY</p>`:'<p class="muted">Todavía no tiene completaciones aceptadas.</p>'}</section><section class="profile-section"><div class="section-head"><h2>Completados</h2><span class="muted small">${completed.length} niveles</span></div>${completed.map(l=>`<a class="levelrow" href="#level/${l.id}"><span class="levelrank ${rankClass(l.rank)}">#${String(l.rank).padStart(2,'0')}<small> UY</small></span><div><div class="levelname">${l.name}</div><div class="creator">AREDL #${l.aredlRank}</div></div><div class="levelpoints">${l.pts}<small>pts</small></div><span class="arrow">↗</span></a>`).join('')||'<p class="muted small">Aún no hay niveles completados.</p>'}</section><section class="profile-section"><h2>Progresos</h2>${progress.map(r=>`<div class="profile-progress"><div>${uyLevels.some(l=>l.id===r.id)?`<a class="player-link" href="#level/${r.id}">${r.level.name}</a>`:r.level.name}<div class="creator">AREDL #${r.level.aredlRank}</div></div><span class="muted">${r.pct}%</span><button class="watch" data-video="progress">Ver video ↗</button></div>`).join('')||'<p class="muted small">No hay progresos aceptados.</p>'}</section>`;bindVideoButtons()}
function activity(){const activityRecords=levels.flatMap((l,id)=>l.records.filter(r=>r.approved&&r.country==='UY').map(r=>({...r,level:l,id})));main.innerHTML=`<a class="back" href="#home">← Inicio</a><div class="page-intro"><div><div class="eyebrow">Comunidad uruguaya</div><h1>Actividad<span class="blue">.</span></h1><p class="muted">Completaciones y progresos aceptados de la comunidad.</p></div></div>${activityRecords.map(r=>`<div class="activity-row"><div><a class="player-link" href="#player/${encodeURIComponent(r.player)}">${r.player}</a> ${r.pct===100?'completó':'avanzó en'} ${uyLevels.some(l=>l.id===r.id)?`<a class="blue" href="#level/${r.id}">${r.level.name}</a>`:r.level.name}</div><span class="${r.pct===100?'percent':'muted'}">${r.pct}%</span><button class="watch" data-video="activity">Ver video ↗</button></div>`).join('')}<p class="muted small" style="margin-top:24px">Actividad de ejemplo, sin fechas reales de publicación.</p>`;bindVideoButtons()}
'''+s[pos:]
s=s.replace("hash==='players'?'players':'home'","(hash==='players'||hash.startsWith('player/'))?'players':'home'")
s=s.replace("else if(hash==='players')playersPage();", "else if(hash==='players')playersPage();else if(hash==='activity')activity();else if(hash.startsWith('player/'))profile(decodeURIComponent(hash.slice(7)));")
s=s.replace("hash==='players'?'Jugadores':hash.startsWith", "hash==='players'?'Jugadores':hash==='activity'?'Actividad':hash.startsWith('player/')?'Perfil de jugador':hash.startsWith")
s=s.replace('</style>','''
.home-grid{row-gap:48px}.hero-intro+.home-grid{margin-top:64px}.page:has(.hero-intro)>.changes{margin-top:64px;padding-top:28px;border-top:1px solid var(--line);margin-bottom:24px}
.player-link:hover{color:var(--blue)}.player-link{display:inline-block;padding-block:8px}
.refined-heading{padding-bottom:28px;border-bottom:1px solid var(--line)}.refined-heading h1{margin-top:14px}.local-placement{font-size:30px;font-variant-numeric:tabular-nums}.local-placement small{font-size:14px;color:var(--muted)}
.record-subtitle{margin-bottom:20px}.watch{color:var(--blue);min-height:44px;white-space:nowrap;border:0;padding:6px}.record-row{grid-template-columns:25px minmax(0,1fr) 50px 95px}.record-row>a{overflow-wrap:anywhere}.badge{border:1px solid var(--line)}
.profile-heading{padding-bottom:32px;border-bottom:1px solid var(--line)}.profile-heading h1{margin-top:16px;overflow-wrap:anywhere}.profile-stats{display:flex;gap:64px;margin-top:32px;flex-wrap:wrap}.profile-stats strong{display:block;font-size:30px;font-weight:500}.profile-stats strong small{font-size:15px;color:var(--muted)}.profile-section{margin-top:40px}.profile-section>h2{margin-bottom:20px}.hardest-link{font-size:26px;display:inline-block;margin-bottom:6px}.hardest-link span{color:var(--blue);font-size:18px;margin-left:15px}.profile-progress,.activity-row{display:grid;grid-template-columns:minmax(0,1fr) 55px 100px;gap:20px;align-items:center;padding:16px 0;border-bottom:1px solid var(--line)}
@media(max-width:760px){.hero.hero-intro{min-height:calc(85svh - 72px)}.hero-intro+.home-grid{margin-top:40px}.page:has(.hero-intro)>.changes{margin-top:40px}.home-grid{gap:40px}.section-head{gap:10px;flex-wrap:wrap}.record-row{grid-template-columns:20px minmax(0,1fr) 40px 85px;gap:7px}.watch{font-size:12px}.profile-stats{gap:24px}.profile-stats strong{font-size:25px}.profile-progress,.activity-row{grid-template-columns:minmax(0,1fr) 40px 85px;gap:8px;font-size:14px}.profile-section .levelrank{font-size:18px}.profile-section .levelrank small{display:block}.refined-heading .detail-rating{justify-content:space-between}.levelrow>div{min-width:0}.levelname{overflow-wrap:anywhere}}
</style>''')
p.write_text(s,encoding='utf-8');Path('work/prototype-check.js').write_text(s.split('<script>')[1].split('</script>')[0],encoding='utf-8')
